#! /usr/bin/perl -T

use Test::More tests => 1;
use Bio::DNAssemble;
use Bio::Seq;

use strict;
use warnings;

my $DNA = Bio::DNAssemble->new();

my $starthsh = {
  '276' => 'TCCTTATTTATACCCGTCCGTATAGTAGGGTACGCAAGGTG',
  '443' => 'GCCGGTTGATCACTGAGGCCCAATTGATGTATCAACATGTG',
  '206' => 'TCCCGACGAGCTGACTTGTGCTATCCTTTCTCCAGGTCTCG',
  '358' => 'TCCTGACCAGGCCGGGCTTCGGCCTGGTGGGCCGGCTCGAG',
  '331' => 'CCCCTTTTCTACGCAGCCGAACTCACATCCTGACCAGGCCG',
  '512' => 'TTTTCTCTAAAAATCCCTTGTGTTTGGTAATCAAACTTCAT',
  '233' => 'TTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGAGACTTTCT',
  '437' => 'AAATGGGCCGGTTGATCACTGAGGCCCAATTGATGTATCAA',
  '277' => 'CCTTATTTATACCCGTCCGTATAGTAGGGTACGCAAGGTGA',
  '462' => 'CCAATTGATGTATCAACATGTGGTTTTTATAAAAAGAGTCG',
  '232' => 'TTTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGAGACTTTC',
  '414' => 'CGGGGCTGGGTCGTTATTCCTTGAAATGGGCCGGTTGATCA',
  '477' => 'ACATGTGGTTTTTATAAAAAGAGTCGTGAGAAGAGTTTTCT',
  '225' => 'GCTATCCTTTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGA',
  '207' => 'CCCGACGAGCTGACTTGTGCTATCCTTTCTCCAGGTCTCGA',
  '330' => 'GCCCCTTTTCTACGCAGCCGAACTCACATCCTGACCAGGCC',
  '263' => 'CGAGACTTTCTATTCCTTATTTATACCCGTCCGTATAGTAG',
  '394' => 'TCGAGTTCTAAAGTGATGGTCGGGGCTGGGTCGTTATTCCT',
  '505' => 'AGAAGAGTTTTCTCTAAAAATCCCTTGTGTTTGGTAATCAA',
  '360' => 'CTGACCAGGCCGGGCTTCGGCCTGGTGGGCCGGCTCGAGTT',
  '419' => 'CTGGGTCGTTATTCCTTGAAATGGGCCGGTTGATCACTGAG',
  '513' => 'TTTCTCTAAAAATCCCTTGTGTTTGGTAATCAAACTTCATT',
  '277' => 'TCCTTATTTATACCCGTCCGTATAGTAGGGTACGCAAGGTG',
  '444' => 'GCCGGTTGATCACTGAGGCCCAATTGATGTATCAACATGTG',
  '207' => 'TCCCGACGAGCTGACTTGTGCTATCCTTTCTCCAGGTCTCG',
  '359' => 'TCCTGACCAGGCCGGGCTTCGGCCTGGTGGGCCGGCTCGAG',
  '332' => 'CCCCTTTTCTACGCAGCCGAACTCACATCCTGACCAGGCCG',
};

my $rhsh = {
  '512' => 'TTTTCTCTAAAAATCCCTTGTGTTTGGTAATCAAACTTCAT',
  '233' => 'TTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGAGACTTTCT',
  '437' => 'AAATGGGCCGGTTGATCACTGAGGCCCAATTGATGTATCAA',
  '277' => 'CCTTATTTATACCCGTCCGTATAGTAGGGTACGCAAGGTGA',
  '462' => 'CCAATTGATGTATCAACATGTGGTTTTTATAAAAAGAGTCG',
  '232' => 'TTTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGAGACTTTC',
  '414' => 'CGGGGCTGGGTCGTTATTCCTTGAAATGGGCCGGTTGATCA',
  '477' => 'ACATGTGGTTTTTATAAAAAGAGTCGTGAGAAGAGTTTTCT',
  '225' => 'GCTATCCTTTCTCCAGGTCTCGAAAAAGTCCCCTTTCCCGA',
  '207' => 'CCCGACGAGCTGACTTGTGCTATCCTTTCTCCAGGTCTCGA',
  '330' => 'GCCCCTTTTCTACGCAGCCGAACTCACATCCTGACCAGGCC',
  '263' => 'CGAGACTTTCTATTCCTTATTTATACCCGTCCGTATAGTAG',
  '394' => 'TCGAGTTCTAAAGTGATGGTCGGGGCTGGGTCGTTATTCCT',
  '505' => 'AGAAGAGTTTTCTCTAAAAATCCCTTGTGTTTGGTAATCAA',
  '360' => 'CTGACCAGGCCGGGCTTCGGCCTGGTGGGCCGGCTCGAGTT',
  '419' => 'CTGGGTCGTTATTCCTTGAAATGGGCCGGTTGATCACTGAG',
  '513' => 'TTTCTCTAAAAATCCCTTGTGTTTGGTAATCAAACTTCATT',
};

my @plaps;
foreach my $id (keys %{$rhsh})
{
  my $oligo = Bio::Seq->new(
      -seq => $rhsh->{$id},
      -id  => $id
  );
  push @plaps, $oligo;
}
my $arr = $DNA->filter_uniqueness(-sequences => \@plaps);
my %thsh = map {$_->id => $_->seq} @$arr;

is_deeply (\%thsh, $rhsh, "filter vmatch");
                                         

